### ISSUE TITLE
Reservoir spill and compensation flows

### ISSUE THREAD

**Issue by snorfalorpagus** [snorfalorpagus/pywr#15]
Add support for river flowing directly into reservoir, and spills and compensation flows.
```
[Catchment] --> [River] --> [Reservoir]
```

**Comment by jetuk** [comment]
We've figured the theory of this out now? It just needs implementing?

**Comment by snorfalorpagus** [comment]
@jetuk Yes, I think so. It would look something like:

* A river abstraction that removes everything (remaining!) from the upstream river network. This abstraction mustn't compete with actually river abstractions upstream (how do we do this?).
* A catchment for the compensation flow from the reservoir. The flow will be a `Parameter` and must also be constrained by the volume in the reservoir.
* A spill, calculated after the supply stage.

Obviously these "nodes" wouldn't really exist, other than in the way the solver formulates the LP.

**Comment by jetuk** [comment]
For simplicity is it with considering a variable for each node in a river that is the flow downstream of that node? Equality constraints will then ensure mass balance? River terminators are then just a river node with no influence and this is the flow which enters the reservoir.

**Comment by snorfalorpagus** [comment]
This is possible now with the new `Storage` class.

**Comment by snorfalorpagus** [comment]
This is demonstrated in https://github.com/snorfalorpagus/pywr/commit/5a8b13117450707a4ee63aab22ed91b1c5913c57
