### ISSUE TITLE
Write a Recorder that buffers results to a file

### ISSUE THREAD

**Issue by jetuk** [snorfalorpagus/pywr#46]
What options have we got for formats,
- CSV
- XLSX
- HDF (via pytables or pyhdf)
- NetCDF
- Numpy

All of these (at least the first 3) are desirable at some point. Need to investigate how easy they are to stream to. Ideally the solve should not be held up (too much) by I/O.

**Comment by snorfalorpagus** [comment]
Are you thinking of a `Parameter` that reads data from a file, or a `Recorder` that writes data to a file?

**Comment by jetuk** [comment]
I guess both, but the original title should have said `Recorder`

**Comment by snorfalorpagus** [comment]
Closed by #76.
