### ISSUE TITLE
Inline Input/Output nodes.

### ISSUE THREAD

**Issue by jetuk** [snorfalorpagus/pywr#66]
How should these work? Should they work at all?

Consider the network,

```
Input 0 -> Input 1 -> Link -> Output 0 -> Output 1
```

**Comment by jetuk** [comment]
I think we agreed that this should be implemented by only applying the costs for Inputs and Outputs when they are the first and last node in a route respectively.

**Comment by rheinheimer** [comment]
I know this is a bit old, but given #688, is this totally resolved? Here's my simplified setup, which seems slightly different but conceptually similar to above:

```
Input 0 ------------------> Link ---------------> Output 1
       \-----> Link ---> Output 0 ---> Link ---->/
```
