### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by snorfalorpagus** [snorfalorpagus/pywr#72]
We have them.

For example, run this and watch the process' memory balloon.

```
import pywr.core
while True:
    pywr.core.Model()
```

**Comment by jetuk** [comment]
`CythonGLPKSolver.__dealloc__` should use `glp_delete_prob` not `glp_free`.

https://github.com/snorfalorpagus/pywr/blob/master/pywr/solvers/cython_glpk.pyx#L30

**Comment by snorfalorpagus** [comment]
Good spot. I think that was the main issue.

This still seems to have a small leak, but I can't work out where.

```
from pywr.core import *

while True:
    model = Model(parameters={
        'timestamp_finish': pandas.to_datetime('2100-12-31'),
    })
    supply = Input(model, 'supply', max_flow=10)
```

**Comment by jetuk** [comment]
Does it happen with lpsolve?

**Comment by jetuk** [comment]
I didn't see the posted code when I commented before. That code doesn't give me a leak with Python 2 or 3 on Linux. I only tested by watching the process memory count.

**Comment by snorfalorpagus** [comment]
We can reopen if necessary.
